log_level = "warn"
outputs = "All"
position = "Top"
app_launcher_cmd = "vicinae toggle"

[modules]
left = [["AppLauncher", "Workspaces"]]
center = ["WindowTitle"]
right = ["MediaPlayer", ["Tray", "Calendar", "Notifications", "Privacy", "Settings", "Clock"]]

[workspaces]
enable_workspace_filling = true

[window_title]
truncate_title_after_length = 80

[clock]
format = "%d.%m.%Y - %H:%M:%S"

[settings]
lock_cmd = "swaylock"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"

[[CustomModule]]
name = "Calendar"
icon = "󰃭"
command = "GTK_THEME=Adwaita:dark yad --calendar --undecorated --close-on-unfocus --no-buttons"

[[CustomModule]]
name = "Notifications"
icon = "󰂚"
command = "swaync-client -t -sw"

[appearance]
style = "Solid"
opacity = 0.55

[appearance.menu]
opacity = 0.9
backdrop = 0.3

# Catppuccin Mocha
[appearance.background_color]
base = "#1e1e2e"
weak = "#1b1b2a"
strong = "#232334"

[appearance.primary_color]
base = "#fab387"
text = "#1e1e2e"

[appearance.secondary_color]
base = "#45475a"
strong = "#585b70"

[appearance.success_color]
base = "#a6e3a1"

[appearance.danger_color]
base = "#f38ba8"
weak = "#f9e2af"

[appearance.text_color]
base = "#cdd6f4"

