log_level = "warn"
outputs = "All"
position = "Top"
app_launcher_cmd = "vicinae"

[modules]
left = [["AppLauncher", "Workspaces"]]
center = ["WindowTitle"]
right = ["SystemInfo", "MediaPlayer", ["Tray", "Clock", "Privacy", "Settings"]]

[workspaces]
enable_workspace_filling = true

[window_title]
truncate_title_after_length = 80

[settings]
lock_cmd = "swaylock"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"

[appearance]
style = "Islands"
